version: "3.8"
# volumes:
#   db-store:
services:
  php:
    build: ./php
    volumes:
      - ../${WORK_DIR}:/var/www/html
      - ./log:/var/log
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - db

  db:
    build:
      context: ./mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      # - db-store:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: hiyoko
      # MYSQL_USER: hiyoko
      # MYSQL_PASSWORD: hiyoko

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: "db"
      UPLOAD_LIMIT: 102400000
    ports:
      - 8888:80
    depends_on:
      - db